backend:
    name: github
    repo: Samuel-Martineau/netlify-cms-test
    branch: main
    open_authoring: true

publish_mode: editorial_workflow

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
    - name: articles
      label: Articles
      folder: content/articles
      create: true
      slug: "{{slug}}"
      fields:
          - label: "Titre"
            name: "title"
            widget: "string"
          - label: "Brouillon"
            name: "draft"
            default: true
            widget: "boolean"
          - label: "Texte"
            name: "body"
            widget: "markdown"
